version: "3.4"

services:
  db:
    image: mariadb:10.5
    container_name: "containerMariaDBFornecedor"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./scriptBancoDeDados:/docker-entrypoint-initdb.d
      - .docker/data1/db:/var/lib/mysql
    ports:
      - 3308:3306
    restart: always